"""Compatibility facade for the TextSimplifier implementation.

The public import remains stable:

    from models.simplifier import TextSimplifier
"""
from .simplifier_parts.base import (
    AUTO_GREEDY_MAX_MEASUREMENTS,
    AUTO_GREEDY_TOLERANCE,
    BLOCKED_SYNONYMS,
    DISCOURSE_DOWNGRADE_MAP,
    DISCOURSE_UPGRADE_MAP,
    DOWNGRADE_TARGET_BUCKET_POLICIES,
    FIREWORKS_MODEL,
    FIREWORKS_NON_STREAM_MAX_TOKENS,
    GRADE_PROFILES,
    GRADE_TARGET_METRICS,
    GRADE_TARGET_SYLLABLES,
    HIGH_GRADE_NARRATIVE_UPGRADE_PHRASES,
    LOW_MID_UPGRADE_BLOCKED_WORDS,
    LOW_MID_UPGRADE_PHRASES,
    MID_GRADE_UPGRADE_PHRASES,
    SUPPLEMENTAL_COMPLEXIFICATIONS,
    SUPPLEMENTAL_SIMPLIFICATIONS,
    TARGET_LOCK_DISPLAY_BAND_TOLERANCE,
    TARGET_LOCK_REPAIR_ROUNDS,
    UPGRADE_TARGET_BUCKET_POLICIES,
)
from .simplifier_parts.core import TextSimplifier

__all__ = [
    "TextSimplifier",
    "AUTO_GREEDY_MAX_MEASUREMENTS",
    "AUTO_GREEDY_TOLERANCE",
    "BLOCKED_SYNONYMS",
    "DISCOURSE_DOWNGRADE_MAP",
    "DISCOURSE_UPGRADE_MAP",
    "DOWNGRADE_TARGET_BUCKET_POLICIES",
    "FIREWORKS_MODEL",
    "FIREWORKS_NON_STREAM_MAX_TOKENS",
    "GRADE_PROFILES",
    "GRADE_TARGET_METRICS",
    "GRADE_TARGET_SYLLABLES",
    "HIGH_GRADE_NARRATIVE_UPGRADE_PHRASES",
    "LOW_MID_UPGRADE_BLOCKED_WORDS",
    "LOW_MID_UPGRADE_PHRASES",
    "MID_GRADE_UPGRADE_PHRASES",
    "SUPPLEMENTAL_COMPLEXIFICATIONS",
    "SUPPLEMENTAL_SIMPLIFICATIONS",
    "TARGET_LOCK_DISPLAY_BAND_TOLERANCE",
    "TARGET_LOCK_REPAIR_ROUNDS",
    "UPGRADE_TARGET_BUCKET_POLICIES",
]
